host: repos.zhiyisoft.com
port: 389
base:
  base: dc=soatour,dc=org
  person: ou=people,dc=soatour,dc=org
attr:
  - displayName
  - uid
  - sn
  - cn
  - userPassword
objectclass:
  - inetOrgPerson
  - organizationalPerson
  - top
  - person
bind:
  dn: cn=admin,dc=soatour,dc=org
  passwd: ts3qdf
